import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { type GraphQLObjectType, type GraphQLSchema, isObjectType } from "graphql";
import { afterAll, beforeAll, expect, test } from "vitest";

// The schema is built from the live Drizzle tables at import time, so the database has to be
// pointed somewhere disposable before anything under server/ is loaded.
const dir = fs.mkdtempSync(path.join(os.tmpdir(), "task-server-docs-"));
process.env.TASK_SERVER_DATA_DIR = dir;

let schema: GraphQLSchema;
let cron: typeof import("../server/scheduler/cron.ts");
let COLUMN_DOCS: typeof import("../server/graphql/docs.ts").COLUMN_DOCS;
let FieldDescriptions: typeof import("../web/__generated__/graphql/descriptions.ts").FieldDescriptions;

beforeAll(async () => {
  const { ensureSchema } = await import("../server/db/migrate.ts");
  await ensureSchema();
  schema = (await import("../server/graphql/schema.ts")).schema;
  cron = await import("../server/scheduler/cron.ts");
  COLUMN_DOCS = (await import("../server/graphql/docs.ts")).COLUMN_DOCS;
  // Generated, gitignored, and regenerated by the `pretest` script — the same file the web app
  // imports. Reading it here is the point: this test is what says the app and the schema are
  // quoting one string.
  FieldDescriptions = (await import("../web/__generated__/graphql/descriptions.ts"))
    .FieldDescriptions;
});

afterAll(async () => {
  await cron.stop();
  fs.rmSync(dir, { recursive: true, force: true });
});

const objectType = (name: string): GraphQLObjectType => {
  const type = schema.getType(name);
  if (!isObjectType(type)) throw new Error(`${name} is not an object type`);
  return type;
};

/**
 * The prose is written once and read three ways, and this is what holds the three together.
 *
 * `server/graphql/docs.ts` is the copy. `describeColumn` puts it on the generated schema, which
 * is what an agent reads in a tool schema on `/mcp`; codegen reads the same schema and emits the
 * map the web app renders under its form fields. Any of the three can be broken on its own —
 * a `describeColumn` hook dropped from `buildSchema`, a plugin dropped from `codegen.ts` — and
 * nothing else would fail: descriptions would just quietly stop arriving.
 */
test("a column is described once and the description arrives everywhere", () => {
  const cases = [
    ["Task", "prompt", COLUMN_DOCS.tasks?.prompt],
    ["Trigger", "event", COLUMN_DOCS.triggers?.event],
    ["Setting", "requestTimeoutSeconds", COLUMN_DOCS.settings?.requestTimeoutSeconds],
    ["McpServer", "env", COLUMN_DOCS.mcpServers?.env],
  ] as const;

  for (const [typeName, fieldName, authored] of cases) {
    expect(authored, `${typeName}.${fieldName} has no entry in docs.ts`).toBeTruthy();

    const field = objectType(typeName).getFields()[fieldName];
    expect(field?.description, `${typeName}.${fieldName} in the schema`).toBe(authored);

    const forType: Record<string, string> = FieldDescriptions[typeName];
    expect(forType[fieldName], `${typeName}.${fieldName} in the generated map`).toBe(authored);
  }
});

/**
 * The write inputs carry it too, which is the half that matters to a caller rather than a reader.
 *
 * A description on `Task.prompt` tells an agent what it just read back. The one on
 * `CreateTaskInput.prompt` tells it what to put there, which is the question it actually has,
 * and the driver reaches every position off the one hook — so this is a check that the hook is
 * still wired rather than that the string is right.
 */
test("the write inputs are described as well as the rows", () => {
  const input = schema.getType("CreateTaskInput");
  if (!input || !("getFields" in input)) throw new Error("CreateTaskInput is not an input type");
  const fields = (
    input as { getFields(): Record<string, { description?: string | null }> }
  ).getFields();
  expect(fields.prompt?.description).toBe(COLUMN_DOCS.tasks?.prompt);
});
