import path from "node:path";
import { eq } from "drizzle-orm";
import { ROOT } from "../paths.ts";
import { db, runMigrations } from "./client.ts";
import { runSteps, runs, settings } from "./schema.ts";

const DEFAULT_SYSTEM_PROMPT =
  "You are a task runner. Carry out the instruction using the tools available to you, " +
  "then report what you did and what you found. Say plainly when something failed.";

/**
 * Brings the database up to the current schema on boot, so a fresh clone — or a fresh postgres
 * — runs with no migration step of its own.
 *
 * The migrations under `drizzle/` are generated by drizzle-kit from `schema.ts` and are the
 * only thing that creates or alters a table; drizzle records which have run in its own
 * `__drizzle_migrations` table and applies each exactly once, so this is safe on every boot.
 * Adding a column is two commands: edit `schema.ts`, then `npm run db:generate`.
 *
 * What follows the migrations is data, not shape.
 */
export async function ensureSchema() {
  await runMigrations(path.join(ROOT, "drizzle"));

  // The settings row is a singleton the UI edits in place, so it has to exist before the UI
  // can load. Column defaults fill the rest in.
  await db
    .insert(settings)
    .values({ id: "default", systemPrompt: DEFAULT_SYSTEM_PROMPT })
    .onConflictDoNothing();

  // A run left `running` by a crash is never going to finish; nothing would ever clear it. The
  // step it died inside is in the same position, and a run whose steps still say `running`
  // would read as though part of it were somehow still going.
  const interrupted = {
    status: "error",
    error: "interrupted by a server restart",
    finishedAt: new Date(),
  } as const;
  await db.update(runSteps).set(interrupted).where(eq(runSteps.status, "running"));
  await db.update(runs).set(interrupted).where(eq(runs.status, "running"));
}
